#-------------------------------------------------------------------------------
# Downloader for SForm by Linn Friberg (https://github.com/linfri)
#-------------------------------------------------------------------------------

library(rdrop2)
library(tools)
library(R.utils)
library(stringi)
library(rvest)
library(httpuv) # just in case, if rdrop2 acts up
library(curl)

#-------------------------------------------------------------------------------
# downloadMusicExt()
#-------------------------------------------------------------------------------

#' @title downloadMusicExt()
#'
#' @description
#' Depending on the file extension downloads files from Dropbox,
#' renames the files, downloads CSVs generated by the form, transforms 
#' the data and generates text files. Optimized for Bandcamp and,
#' specifically, Kalamine Records submission process.
#' 
#' @param tokenURL Path to the token, passed from downloadMusic()
#' @param targetFolder A folder for downloads, passed from downloadMusic()
#' @param extension Supported file format (wav, aiff, flac)
#' 
#' @return 
#' Returns a data frame with data from the form, per extension.
#'
#'

downloadMusicExt <- function(tokenURL, targetFolder, extension) {
  
  # Determines extensions and if called directly checks params.
  if (extension == "wav") {
    ext0 <- "0.wav"
    ext1 <- "*.wav"
    ext2 <- ".wav"
  }
  if (extension == "flac") {
    ext0 <- "0.flac"
    ext1 <- "*.flac"
    ext2 <- ".flac"
  }
  if (extension == "aiff") {
    ext0 <- "0.aiff"
    ext1 <- "*.aiff"
    ext2 <- ".aiff"
  }
  if (extension == "") stop("extension has to be specified.")
  if (tokenURL == "") stop("token has to be specified.")
  if (targetFolder == "") stop("target folder has to be specified.")
  
  # Checks whether there's internet connection.
  if(!curl::has_internet()) stop("Please connect to the internet!")
  
  # Checks whether the Downloads folder exists and, if not, creates it.
  if(!dir.exists(targetFolder)) dir.create(targetFolder)

  # Preparing data structures and then downloading & renaming files.
  token <- readRDS(tokenURL)
  x <- drop_search(ext1, dtoken = token)
  dlNames <- vector("list", length = length(x[["matches"]]))
  dlCSV <- data.frame()

  print(paste0("Downloading ", extension, " files..."))
  for (i in seq_along(x[["matches"]])) {
    if (x[["matches"]][[i]][["metadata"]][[".tag"]] == "file" &&
      x[["matches"]][[i]][["metadata"]][["name"]] == ext0) {
      dlNames[i] <- basename(dirname(x[["matches"]][[i]][["metadata"]][["path_display"]]))
      drop_download(x[["matches"]][[i]][["metadata"]][["path_display"]], local_path = targetFolder, dtoken = token)
      renameFile(paste0(targetFolder, ext0), paste0(targetFolder, dlNames[i]))
    }
  }

  # Removing empty entries.
  newdlNames <- dlNames[lapply(dlNames, length) > 0]

  # Downloading CSVs.
  print("Downloading csv files...")
  for (i in seq_along(x[["matches"]])) {
    if (x[["matches"]][[i]][["metadata"]][[".tag"]] == "file" &&
      file_ext(x[["matches"]][[i]][["metadata"]][["name"]]) == "csv") {
      dlCSV <- rbind(dlCSV, drop_read_csv(x[["matches"]][[i]][["metadata"]][["path_display"]], dtoken = token))
    }
  }

  # Generating text files, data wrangling.
  print("Generating text files...")
  for (i in seq_along(newdlNames)) {
    oldName <- paste0(targetFolder, newdlNames[i])
    newName <- paste0(targetFolder, dlCSV$Artist[i], " - ",
      dlCSV$Track[i], ext2)
    if (oldName != newName) renameFile(oldName, newName)

    if (extension == "wav") {
      newTxtName <- paste0(stri_sub(newName, from = 1, to = stri_length(newName) - 4, ), ".txt")
    }
    if (extension == "flac" | extension == "aiff") {
      newTxtName <- paste0(stri_sub(newName, from = 1, to = stri_length(newName) - 5, ), ".txt")
    }

    textInfo <- c(
      paste0("Country: ", dlCSV$Country[i], "\n"),
      paste0("More about ", dlCSV$Artist[i], ": ", dlCSV$Website[i], "\n")
    )

    writeLines(textInfo, newTxtName)
    
  }
  
  # Returning the data frame.
  return(dlCSV)
}

#-------------------------------------------------------------------------------
# downloadMusic()
#-------------------------------------------------------------------------------

#' @title downloadMusic()
#'
#' @description
#' Calls downloadMusicExt() for all the supported formats, generates
#' the tracklist sorted in alphabetical order, album description,
#' album credits, plus a frequency table (artists per country).
#' Optimized for Bandcamp, specifically, Kalamine Records submission process.
#' 
#' @param dlToken Path to the token, default from generateToken()
#' @param dlFolder A folder for downloads, default Downloads\\
#' 
#' @return 
#' Returns a text message after generation.
#'
#'

downloadMusic <- function(dlToken = "ee977806d7286510da",
                          dlFolder = "Downloads\\") {
  
  print("Downloading all the files from Dropbox...")
  dfWAV <- downloadMusicExt(dlToken, dlFolder, "wav")
  dfFLAC <- downloadMusicExt(dlToken, dlFolder, "flac")
  dfAIFF <- downloadMusicExt(dlToken, dlFolder, "aiff")

  # Combining and sorting the output from downloadMusicExt()
  dfAll <- rbind(dfWAV, dfFLAC, dfAIFF)
  dfAll <- dfAll[order(dfAll$Artist, dfAll$Track), ]
  dfAll <- as.data.frame(cbind(dfAll$Artist, dfAll$Country, dfAll$Track))

  print("Generating tracklist...")
  writeLines(
    paste0(dfAll[, 1], " (", dfAll[, 2], ") - ", dfAll[, 3]),
    paste0(dlFolder, "Tracklist.txt")
  )

  print("Generating stats...")
  write.csv(table(dfAll$V2), file = paste0(dlFolder, "Stats.csv"))
  
  print("Generating album descriptions...")
  writeLines(html_text(read_html("compilationcall.txt")),
             paste0(dlFolder, "AlbumInfo.txt"))
  credits <- c(paste0("Compiled by ___ in ", format(Sys.time(), "%B %Y"), "."),
               "Mastered by ___.",
               "Image by ___ from Pixabay/Unsplash (Month YEAR)",
               "Text and graphic design by ___.\n",
               "All tracks were created and produced by the artists involved.",
               "Please refer to the individual tracks for more information.")
  writeLines(credits, paste0(dlFolder, "AlbumCredits.txt"))

  return("Success!")
}
